### ISSUE TITLE
ES6 inside umd folder

### ISSUE THREAD

**Issue by fstn** [tinode/tinode-js#12]
I don't know why but there is still ES6 keyword in UMD folder (let ... const ...) and it fail to compile react script with error unable to minify.

As mention here  https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#npm-run-build-fails-to-minify , I update my react-script to 2.0 to resolve the issue.

It might be better to have only ES5 in UMD folder. what do you think about it?

**Comment by or-else** [comment]
I'm by no means an expert in JS. If you say that there should not be ES6 in UMD then I agree :)

Can you send a pull request or otherwise suggest what needs to be changed?

**Comment by fstn** [comment]
https://github.com/tinode/tinode-js/pull/13
