### ISSUE TITLE
Tinode exit with error

### ISSUE THREAD

**Issue by fstn** [tinode/tinode-js#17]
My server failed with only this message:

`invalid character ']' looking for beginning of value`

Any ideas?

**Comment by or-else** [comment]
Can you show the full server-side and client-side logs? If the server is in docker you can get the logs by doing
```
docker exec -it name-of-the-running-container /bin/bash
tail -30 /var/log/tinode.log
```

**Comment by fstn** [comment]
I'm not able to extract the full logs because the docker is launched by Kubernetes and restart all the time ...

**Comment by fstn** [comment]
The client do nothing... The error appends at the startup

**Comment by fstn** [comment]
Ok I deleted rethinkdb and it's ok now :/
