### ISSUE TITLE
[Bug] topic.unread=NaN when there are 0 read messages

### ISSUE THREAD

**Issue by ejbp** [tinode/tinode-js#20]
**Problem:**
<img width="606" alt="screenshot 2019-02-06 at 17 41 54" src="https://user-images.githubusercontent.com/2060105/52361754-dfa14700-2a36-11e9-8322-df6f4854ae9e.png">

**How to replicate the problem?**

![bug1_c](https://user-images.githubusercontent.com/2060105/52363637-11b4a800-2a3b-11e9-8467-7640fbbd0d59.gif)

**Analyses:**
After going a little deep in the src code, I noticed that when it's the first time that the contacts are connected (one to one or with a new group) if you read 0 messages, meaning, when you never send the "read" notification, if you receive new messages then the topic.read doesn't exists wich will cause the unread to be a NaN. 

I believe the bug is on the 'setMsgReadRecv' function on this piece of code:
```
       case 'msg':
            oldVal = cont.seq;
            cont.seq = cont.seq ? Math.max(cont.seq, seq) : seq;
            cont.unread = cont.seq - cont.read;
            if (!cont.touched || cont.touched < ts) {
              cont.touched = ts;
            }
            doUpdate = (oldVal != cont.seq);
            break;
```
wich if you modify to the one below, the problem is solved:
```
       case 'msg':
            oldVal = cont.seq;
            cont.seq = cont.seq ? Math.max(cont.seq, seq) : seq;
            cont.read = cont.read | 0; //<----------------------here is the change
            cont.unread = cont.seq - cont.read;
            if (!cont.touched || cont.touched < ts) {
              cont.touched = ts;
            }
            doUpdate = (oldVal != cont.seq);
            break;
```

**Comment by or-else** [comment]
Thanks a lot, fixed: https://github.com/tinode/tinode-js/commit/1f6ca864b77685a326c1182ff25b98ee36768841

**Comment by or-else** [comment]
The fix has been released as a part of https://github.com/tinode/tinode-js/releases/tag/v0.15.13-rc1
