### ISSUE TITLE
Topic `read`, `recv`, `unread` properties are reset on subscription

### ISSUE THREAD

**Issue by tiagoalves** [tinode/tinode-js#21]
### Summary

I'm subscribing to an existing topic and the response `ctrl` message seems to be resetting the `read`, `recv`, `unread` properties in the "me" topic cache, consequently, when the `topic.onInfo` event is next triggered, my topic indicates that all messages are unread.

### Detailed description

* Connect to the server and log in
* Subscribe to me
    * `out: {"sub":{"id":"68013","topic":"me","get":{"what":"sub desc"}}}`
* One of the responses includes info about subscriptions. Everything is correct and my `read/recv/unread` values are correct.
    * `in: {"meta":{"id":"68013","topic":"me","ts":"2019-02-27T13:19:30.955Z","sub":[...]}}`
* Now I subscribe to a specific topic:
    * `out: {"sub":{"id":"68014","topic":"usrIfaOwzqcliA","set":{"sub":{"mode":"JRWPASD"}},"get":{"data":{"limit":100},"sub":{"ims":"2019-02-21T15:22:34.443Z"},"desc":{"ims":"2019-02-21T15:22:34.443Z"},"what":"data sub desc"}}}`
* I believe that the handling fo the `ctrl` response triggers the reset of the `read/recv/unread` values in the cache.
    * `in: {"ctrl":{"id":"68014","topic":"usrIfaOwzqcliA","params":{"acs":{"want":"JRWPA","given":"JRWPA","mode":"JRWPA"}},"code":200,"text":"ok","ts":"2019-02-27T13:24:03.752Z"}}`

This appears to be what happens:

I call `tinode.getTopic("usrIfaOwzqcliA")` and the topic is correctly fetched from the tinode cache [here](https://github.com/tinode/tinode-js/blob/a722117d4c8b43eca21e6d4a112196cd0cab73bf/src/tinode.js#L2269).

When the subscription response `ctrl` message is received, it is handled [here](https://github.com/tinode/tinode-js/blob/a722117d4c8b43eca21e6d4a112196cd0cab73bf/src/tinode.js#L3169). Since `_new === true`, the messages is also handled [here](https://github.com/tinode/tinode-js/blob/a722117d4c8b43eca21e6d4a112196cd0cab73bf/src/tinode.js#L3182). Consequently, since no `read/recv/unread` is passed to this handler, these values are reset [here](https://github.com/tinode/tinode-js/blob/a722117d4c8b43eca21e6d4a112196cd0cab73bf/src/tinode.js#L4325).

I think the problem is actually in this [last point](https://github.com/tinode/tinode-js/blob/a722117d4c8b43eca21e6d4a112196cd0cab73bf/src/tinode.js#L4325) and not even in the fact that `_new` is `true` even though I was expecting it to be false. Every time a message handled there, the `read/recv/unread` are not passed as a parameter and they are then reset there.

### Potential fix

This change fixes the issue for me in the short term. It basically only messes with the `read/recv/unread` properties if `seq` is even provided.

```
        // Ensure the values are integer.
        if (typeof sub.seq !== 'undefined') {
          sub.seq = sub.seq | 0;
          sub.recv = sub.recv | 0;
          sub.read = sub.read | 0;
          sub.unread = sub.seq - sub.read;
        }
```

**Comment by or-else** [comment]
Thanks for the report!

Re `_new`: `_new == true` means the topic object was created but not yet synced with the server. It does not mean this is a new subscription.

**Comment by or-else** [comment]
[Released](https://github.com/tinode/tinode-js/releases/tag/v0.15.13-rc3)
