### ISSUE TITLE
In p2p topics, other user's read/recv values overwrite our own in the local cache

### ISSUE THREAD

**Issue by tiagoalves** [tinode/tinode-js#22]
My Tinode SDK version: `0.15.13-rc1`

### Scenario

In my custom chat client, I'm trying to implement the chat list similar to other popular chat apps. I want to show the last received message below each topic's name.

When I get an indication that a new message was sent to a given topic (`in: {"pres":{"topic":"me","src":"usrIfaOwzqcliA","what":"msg","seq":490}}`), I automatically subscribe to the topic,  fetch the message and keep subscribed to the topic (for now, at least).

I mark the message as received (but not read) (`out: {"note":{"topic":"usrIfaOwzqcliA","what":"recv","seq":490}}`).

#### Group Topics

As expected, other chat participants send `note` messages indicating their new `read/recv` values (`in: {"info":{"topic":"grpyr3cOEQPGtk","from":"usrIfaOwzqcliA","what":"recv","seq":12}}`) which triggers the `topic.onInfo()` callback on my side. Consequently, the topic's `recv`, `read` and `unread` values still reflect my own user's values (in perspective to the `me` topic). The `me.onContactUpdate()` callback is not triggered (as expected).

#### P2P Topics

However, for p2p topics, when the other user indicates `recv` or `read` (`in: {"info":{"topic":"usrIfaOwzqcliA","from":"usrIfaOwzqcliA","what":"recv","seq":493}}`), the `me.onContactUpdate()` callback _is_ triggered which messes up my own user's `read/recv/unread` values.

I would expect the same behaviour as in the chat groups.

If I disconnect and connect again, I receive the topics meta information (`in: {"meta":{"id":"73606","topic":"me","ts":"2019-02-28T11:36:09.44Z","sub":[...] }}`) again and the `read/recv/unread` messages are correct again for my user.

### Fix

The problem seems to be that in p2p topics, the topic has the same id as the other user, so [here](https://github.com/tinode/tinode-js/blob/73d63245e7a0ae87dff10c7496b4fa82d7339bb7/src/tinode.js#L4272) we're updating our own view of a p2p topic with the other user's info.

**Comment by or-else** [comment]
This https://github.com/tinode/tinode-js/blob/73d63245e7a0ae87dff10c7496b4fa82d7339bb7/src/tinode.js#L4274 is just plain wrong. I'll fix it.

**Comment by or-else** [comment]
> I want to show the last received message below each topic's name

I thought about it too. I wanted to save message preview as `private.comment` then it would be automatically available on all clients. But it would require subscription to all topics and would double the traffic. So I left it for the future.

**Comment by or-else** [comment]
[Released](https://github.com/tinode/tinode-js/releases/tag/v0.15.13-rc3)
