### ISSUE TITLE
Update documentation to reduce the entry threshold (simplified).

### ISSUE THREAD

**Issue by VictorV96** [tinode/tinode-js#25]
Simplification methods:
1) Create a test server (or use the current)
1.1) Print the api key for the test server in the documentation.
1.3) Correct the error in the initial template on line 33 (* me.subscribe ({get: {desc: {}, sub: {}} *);). * ===}

2) Write the simplest examples of the basis of the messenger:
2.1) Login / Registration
2.2) Getting the list of contacts (right column in the web version) and their ID.
2.3) Sending a message to a user / group by his ID.
2.4) Sending a file to a user / group.
2.5) Getting a list of messages.
2.6) Obtaining information about the user by his ID.
2.7) Delete Editing.

If possible, add your instructions gradually adding new information. I will not be able to do this, since I myself did not understand your system.

**Comment by or-else** [comment]
I'm not sure what this is about. If you are suggesting to take these steps then:

1. That's the docker container.
1.1. It's in the tinode.conf. There is not a lot of value in changing it.
1.3 Which template are you referring to?

2. Basically, this project is all of that. You have to be a bit more specific. Are you referring to `tn-cli` or something else?

**Comment by VictorV96** [comment]
Not. I'm talking about the documentation with examples. That is, in order to log in, you need to send a request ws: // request {"login": {"id": "eve123", "scheme": "basic", "secret": "ZXZlOmV2ZTEyMw =="}

**Comment by or-else** [comment]
Like this?
https://github.com/tinode/chat/blob/master/docs/API.md
