### ISSUE TITLE
Websocket problems

### ISSUE THREAD

**Issue by pwFoo** [tinode/tinode-js#26]
Hi @or-else,

tried first steps with tinode.js. It failed to connect because of not accepted api key.

Created and validated by keygen tool inside of running docker container, but server log says api key is missing / invalide. Client get a 403. 

Tried with local installed xamp (127.0.0.1) and also moved html file to static directory (tested because of cross origin to have the same domain).

So what could be wrong?
Keygen generates v1 api key. wss url says v0. Other stuff looks ok to me

**Comment by or-else** [comment]
Have you updated the `tinode.conf` with the HMAC salt?
https://github.com/tinode/chat/blob/master/server/tinode.conf#L22

Try validating the key with `keygen -validate`.

**Comment by pwFoo** [comment]
So I need to update salt or better use the salt value from config file? Old api key (default web client) should still work with it.

**Comment by pwFoo** [comment]
keygen -validate Outputs key + salt. Looks similiar to keygen output to create a new key.

**Comment by or-else** [comment]
> So I need to update salt

When you generate the key you get the key and salt. Copy the salt to the config file.

> keygen -validate Outputs key + salt. Looks similiar to keygen output to create a new key.

Please read what it prints in its entirety.

**Comment by pwFoo** [comment]
And old key / salt (default web client?) still validate if I change salt in config?

**Comment by or-else** [comment]
> And old key / salt (default web client?)

Yes, use the old salt for the default API key. If you change the API key you have to updated `tinode.conf` with the new salt.

> still validate if I change salt in config

I don't understand the question.

**Comment by pwFoo** [comment]
If I understand it the right way I can use ONE api key. Old one with the original salt OR the new key if I adjust the salt in the config file.

I tried to use both. The old key for default web client and the new one with my tinode.js test.

Because there is only one salt in config I only can use one of the two keys.

**Comment by or-else** [comment]
Correct, the server can use only one key salt at a time.

**Comment by pwFoo** [comment]
Ok, thanks! Fixed.
