### ISSUE TITLE
node js compatibility

### ISSUE THREAD

**Issue by b1f6c1c4** [tinode/tinode-js#28]
[This paragraph](https://github.com/tinode/tinode-js/blob/master/src/tinode.js#L241-L257) causes the following error in nodejs:
`Error: XMLHttpRequest is not defined (503)`

I recommend using axios for this.

**Comment by or-else** [comment]
XMLHttpRequest is used only in long polling. Long polling is a fallback mechanism when websockets are not available. Given that you fully control your node environment, you can always include a websocket provider and consequently long polling won't ever be needed. Have you provided a websocket implementation as suggested?
https://github.com/tinode/tinode-js/blob/master/README.md#node-js-compatibility

**Comment by or-else** [comment]
Actually XMLHttpRequest is also used in file uploads, so I suppose it needs to be polyfilled too.
And URL.createObjectUrl() needs to be polyfilled. I'll make the changes in the SDK.

**Comment by or-else** [comment]
OK, I've updated the SDK to allow polyfilling of `XMLHttpRequest` too and added instructions how to do it
. 
The `URL.createObjectURL` is still not polyfilled and I don't have time to work on it right now. We do not use this code under Node. You are welcome to send a pull request.

**Comment by b1f6c1c4** [comment]
Related: https://github.com/nodejs/node/issues/16167

**Comment by or-else** [comment]
A full replacement is great, but a workaround would be sufficient too. Maybe an alternative way of downloading when createObjectURL is not available. Or maybe have createObjectURL return a data URL https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URIs

**Comment by or-else** [comment]
The original issue with `XMLHttpRequest` has been resolved. The `createObjectURL` was added in Node v16.7.0.

Let's close this issue as it is no longer clear what's exactly missing. Please file a new issue if something is still broken when running in Node environment.
