### ISSUE TITLE
Having problem in updating "me" or other user's information

### ISSUE THREAD

**Issue by rxmoein** [tinode/tinode-js#32]
## What do I want to do?
Update my account's information without using password when I have logged in.

## What's the problem?
I need to know what's the correct way to update my account's information. I tried some functions introduced in js-doc but it didn't work for me.

 ## What did I do?
First I used `getMeTopic` to see my account's info and I found out the public field is `null`.
Then I needed to add a name field to it by using `setMeta` function. Every time I tested it, I got `not modified` response.
I also found a function named `updateAccountbasic` but it needs user id, username, and password. I can't ask for password every time that user wants to modify his / her account information. 

So simply, how can I update my account's information?

**Comment by or-else** [comment]
Did you subscribe to `me` topic?

Take a look at this conversation:
https://github.com/tinode/chat/issues/478

**Comment by rxmoein** [comment]
Cool, Thanks I didn't subscribe. Now It worked.
I have a second question, does the SDK have a types package for typescript? I'm using it in an angular project

**Comment by or-else** [comment]
Everything that exists is here.

You are welcome to contribute one.

**Comment by rxmoein** [comment]
I'm interested to contribute. Thanks for your help.

**Comment by rxmoein** [comment]
@or-else Can you tell me why when I subscribe to this topic the information is not loaded? I see the data is loaded only when I have changed the information?

**Comment by or-else** [comment]
I don't understand the problem. Please describe it step by step or show the log.

**Comment by rxmoein** [comment]
It's fixed now. I was not sending the `getParams`
