### ISSUE TITLE
callbacls is not defined

### ISSUE THREAD

**Issue by rxmoein** [tinode/tinode-js#33]
**Describe the bug**
In this method `this.tinode.newTopic` on line 3414 the code is using an undefined variable.
![Screenshot from 2020-07-09 12-22-44](https://user-images.githubusercontent.com/32099630/87012964-2fadab80-c1df-11ea-81e4-55d45c7fa03e.png)

**To Reproduce**
just use the `newTopic` method

**Screenshots**
![Screenshot from 2020-07-09 12-26-13](https://user-images.githubusercontent.com/32099630/87013121-6aafdf00-c1df-11ea-8718-3986abc4f19d.png)

**Environment:**
 - OS: Linux
 - Browser: Chrome
 - SDK Version ` * @version 0.16`

**Comment by or-else** [comment]
Thanks, fixed in `devel`.
