### ISSUE TITLE
ranges is constant

### ISSUE THREAD

**Issue by sasharp** [tinode/tinode-js#37]
Hello, in drafty.js line 587 ranges is constant. Please change it. I found more bugs and have fixes for. How can I send PRs to the repo?

**Comment by or-else** [comment]
Thanks, fixed: https://github.com/tinode/tinode-js/commit/fb97f63dd0f63719d746028f4fa5112e61caf79f

> How can I send PRs to the repo?

Just send the PR against the `devel` branch. 

Or do you mean how to send a PR on Github? Then here is the instructions: https://opensource.com/article/19/7/create-pull-request-github
