### ISSUE TITLE
IndexedDB limits integration with React Native

### ISSUE THREAD

**Issue by kisulken** [tinode/tinode-js#45]
Hello,

In the upcoming version you have integrated IndexedDB for caching. By doing this you are limiting integration of the SDK with react/native. I understand that intent of the SDK is to support web version, however myself and possibly others will find themselves in a situation where we can no longer update the SDK due to incompatibility of IndexedDB with react.

I do not have a good solution on hands right now but just wanted to let you know about this issue.

**Comment by or-else** [comment]
It's not a hard requirement. You can disable the DB or provide a shim.

**Comment by kisulken** [comment]
@or-else could you please advise on how to disable it? Is there a specific configuration field that has to be defined?

**Comment by or-else** [comment]
It's initialized right here:
https://github.com/tinode/tinode-js/blob/4aa1375aa68efd8ccba6f9bc8aa6715fb4d114ee/src/tinode.js#L1282-L1284

So, set `config.persist` to `false` or `undefined`.
