### ISSUE TITLE
CommonJs or ES6 export

### ISSUE THREAD

**Issue by imikiani** [tinode/tinode-js#5]
Could you please provide a way to export the library, so that we can import it in the Nodejs based applications? 
Regards.

**Comment by or-else** [comment]
Any update on this?

**Comment by imikiani** [comment]
Sorry for the delay.

In our company we've decided to use the library and make it modular and also write it in ES6. Our goal is using the library in a React Native application. Could you please let us convert the library in ES6?

Also, if our React Native project would finished, we could published it on the github.

**Comment by or-else** [comment]
> Could you please let us convert the library in ES6?

Sure. What do I need to do to help you? As I said, I don't have much experience with Node. 

> Also if we start the React native or the ES6 projects, we will mirror them on the github.

Great.

**Comment by or-else** [comment]
I assume this is no longer relevant. If not, let me know and I'll reopen the issue.
