### ISSUE TITLE
Uncaught TypeError: d[e].props is not a function

### ISSUE THREAD

**Issue by Ovizro** [tinode/tinode-js#72]
**Uncaught TypeError: d[e].props is not a function**
tinode-js crashed when encountering this exception.

**To Reproduce**
1. Send a Drafty message with entity `FM` and set `su` field
2. See error

**Expected behavior**
I hope tinode-js doesn't crash on this exception, consider simply ignoring this exception.

**Screenshots**
![image](https://github.com/tinode/tinode-js/assets/58851732/9107d585-0129-441e-b5b1-b0efa825c259)

**Environment (please complete the following information):**
 - OS: Windows 10
 - Browser: Edge
 - SDK Version: 0.22.9

**Console log**
![image](https://github.com/tinode/tinode-js/assets/58851732/011b51c5-22c4-482b-8bf1-23f8fd8a7319)

**Additional context**
I speculate that this may be related to this piece of code:
https://github.com/tinode/tinode-js/blob/6cdc1963da5043e3f735a49b8671e15c17c2d3d2/src/drafty.js#L1913

**Comment by Ovizro** [comment]
I tried a simple fix of adding `&&d[e].props` to the conditional statement on the previous line, which successfully prevented the crash.

**Comment by or-else** [comment]
1. Which version of Tinode SDK is this?
2 Can you reproduce the problem with `tinode.dev.js`?
3. What are the steps to reproduce the problem?

**Comment by or-else** [comment]
This will probably fix it:
https://github.com/tinode/tinode-js/commit/fc01ef585da6c935e60e21460faf90cbb1dc598f

**Comment by Ovizro** [comment]
Thanks.
The recurrence is basically as I said above, the chat interface crashes after receiving a specific message.  This is how I did it before. Since I am now developing a chatbot framework that can be used in tinode, I followed the instructions in drafty.md and sent a message with FM entity and attached data: {su: true} for testing.  When I received this message in the chat interface with the bot, the chat interface immediately crashed, leaving only the background.  The same situation occurred again when I later entered the chat interface of the bot from the main interface.
As for debugging in development mode, please wait a moment.

**Comment by Ovizro** [comment]
The stack traceback is as follows:
![image](https://github.com/tinode/tinode-js/assets/58851732/7642b7dc-2fac-4312-8bd0-df7e54222569)

And the console log at the time of the crash:
![image](https://github.com/tinode/tinode-js/assets/58851732/f9aaae81-8b4d-4d03-8aaf-d15eb7a714a1)
![image](https://github.com/tinode/tinode-js/assets/58851732/7f0d9807-bd83-4387-b30b-56ca6e873452)

**Comment by or-else** [comment]
Did you have a chance to test the fix I posted earlier?

**Comment by Ovizro** [comment]
I tried copying the `src` and `umd` folders into the container and it did behave fine and no longer crashed.
