### ISSUE TITLE
download large file isn't using the server host

### ISSUE THREAD

**Issue by Nathan-Kr** [tinode/tinode-js#73]
https://github.com/tinode/tinode-js/blob/6cdc1963da5043e3f735a49b8671e15c17c2d3d2/src/large-file.js#L220

When downloading an attachement, the front-end url is used rather than this._tinode._host.

Is it possible to prefix the url with this._tinode._host such as in the upload logic:
https://github.com/tinode/tinode-js/blob/6cdc1963da5043e3f735a49b8671e15c17c2d3d2/src/large-file.js#L184C71-L184C89

The bug occurs when the backend isn't hosted on the same domain as the frontend

**Comment by or-else** [comment]
The only place where `LargeFileHelper.download()` is called is here:
https://github.com/tinode/webapp/blob/5faedc35f3b27bff11f50fc1a388f5bef1ebd2fc/src/widgets/attachment.jsx#L21
And it's only called when the URL is relative. 

The case of an absolute URL is handled below:
https://github.com/tinode/webapp/blob/5faedc35f3b27bff11f50fc1a388f5bef1ebd2fc/src/widgets/attachment.jsx#L71

So, could you describe what exactly you are doing?

**Comment by Nathan-Kr** [comment]
In my case i host the tinode server and the tinode webapp on different domains. Therefore the frontend using tinode-sdk wich is using xhr.open resolve the webapp hostname to process the request.

I think the bug is too particular to be considered as an issue.
