### ISSUE TITLE
SDK examples in [pure] JavaScript

### ISSUE THREAD

**Issue by B0BAI** [tinode/tinode-js#9]
Hi,

I'm wondering if it's possible to see examples of real usage of JS SDK in Pure Javascript instead of using a Framework like [React](https://github.com/tinode/webapp).

We are working on a project and intend on using Tinode but I  don't have any knowledge of React JS. Hence, following the example is quite a curve for me.

I reviewed the [JS Doc](http://tinode.github.io/js-api/) but no example to guide.

Can you help in any way?

**Comment by or-else** [comment]
The SDK is pure JS. It does not use React and has no other dependencies.

I don't have an example of a non-React webapp. It's just not very practical to create one. 

As for usage, take a look at the following lines of code:

Initialize Tinode
https://github.com/tinode/webapp/blob/master/index.js#L4401

Login
https://github.com/tinode/webapp/blob/master/index.js#L4558

On successful login
https://github.com/tinode/webapp/blob/master/index.js#L4607

**Comment by or-else** [comment]
Also there is a very basic pure js example in https://tinode.github.io/js-api/

**Comment by B0BAI** [comment]
Thanks!!
